services:
  app:
    build:
      context: .
      target: dev
    container_name: product_api_app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: php artisan serve --host=0.0.0.0 --port=8000

  postgres:
    image: postgres:16
    container_name: product_api_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: products
      POSTGRES_PASSWORD: products
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
